[package]
name = "xlogger"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../../domain-lib/interface" }
rref = { path = "../../../../domain-lib/rref" }
basic = { path = "../../../../domain-lib/basic",  default-features = false  }
log = "0"